### PR TITLE
fix: use test-uses

### LINKED ISSUE #19: action hub builder should use --test-uses as argument
https://github.com/jina-ai/action-hub-builder/blob/319bc29b67a8fefbb57543a53ce6d4b478f02f8b/entrypoint.sh#L48

### PR DESCRIPTION
**Pull request by JoanFM**

### CODE REVIEW

**Review by nan-wang — APPROVED** [review]
LGTM👍

**Comment by nan-wang** [comment]
wait. It is better to make whether running tests to be an input option. In the case of using hub-builder together with hub-updater, the tests have already been run when building the Docker image because we have `RUN pip install pytest && pytest -v` in all the Dockerfiles

**Comment by JoanFM** [comment]
> wait. It is better to make whether running tests to be an input option. In the case of using hub-builder together with hub-updater, the tests have already been run when building the Docker image because we have `RUN pip install pytest && pytest -v` in all the Dockerfiles

test uses do not run unit tests, try to load the Executor in a Flow and see it does it successfully.

**Comment by nan-wang** [comment]
> > wait. It is better to make whether running tests to be an input option. In the case of using hub-builder together with hub-updater, the tests have already been run when building the Docker image because we have `RUN pip install pytest && pytest -v` in all the Dockerfiles
> 
> test uses do not run unit tests, try to load the Executor in a Flow and see it does it successfully.

aha, yes, you are right.

**Pull request merged**
